services:
  postgres:
    container_name: postgres-clean-nest
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: clean-nest
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres

volumes:
  postgres_data: